server:
  port: 8088

spring:
  application:
    name: travel_guide
  #    配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/travel_guide?useUnicode=true&characterSet=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，stat：监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许报错，java.lang.ClassNotFoundException: org.apache.Log4j.Properity
      #则导入log4j 依赖就行
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  #接入ai
  ai:
    openai:
      api-key: sk-30181d8ec8ab4bd197255db5deb12fc6 # deepseek密钥
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  mvc:
    async:
      request-timeout: 180000

deepseek:
  historyCount: 5

com:
  own:
    properties:
      uploadType: local
      login:
        isNeedCaptcha: false
        errorMaxCount: 3
      jwt:
        key: travel_guide
        expireTime: 36000000000

mybatis-plus:
  #  配置逻辑删除默认值
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mappers/*.xml

logging:
  config: classpath:logback-spring.xml

# 沙箱支付配置
alipay:
  appId: 9021000162691431 # 应用id
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnqLEDrhJqH4PLAuPO612PDUHmIMJbs+6uJuijM9V7P7PjPboKZJYz4iSDRU9m1WhY09dqIxL6FvQNsGDX/zWzieRGebRBg+8vyQ0QwH1sK5EXsxVI2j/nztEAfMoOoDUlSSi3sD5mkKRtoIrgs8LojUrQkpI53L6zvGfEJe7r3qoXDy4DdXOAoNMVbJtUa3qx83ol3PEdmPAftCIEyoyZZw7CsUtnK5cxXZQu3ynaW1EX3sSO1lzB+J2fsUM5fzg+ngZ/S9NlhZoJCow3b0ThVSSppB6HkoSL2Wu/tZnuhi8b5mh6vcp86R1wy/pFazDR+PCM3yOb6tfCrD9toBKjAgMBAAECggEAUuJbeFVC90HTNracBnxnCURlkq4ZR5qBYYkMszn5zO9mL+4hHegyNT4UDO1j3pOb/WXk9ayXQhm811Od3MpnMvX1az3ZdhYSVg5PrjtrBeHX3d6DpDt5IlElE9edUHO1MlSjk4PGpY/WKfgXEBTuQ2cuWERNk9tkT5jRt6+FGQdvLcjOQ9FR/IYB7e7xpwKWE+9NfWkoZsy5kJmiF7fSDCTZUMUj/SylGLfL6mr7/M9/GD/m/KD4bOsgI0CtMIXqu7HV4Dvcc4dLpxzht6zll1bCyxwiDzDtSIDvSl6ILyqjYmNLLLxHRLG3JKYXyqw1wUWDE0XTWqdy3pUFfCyHaQKBgQD8puuObuzX28OsuS+vVPYvKa+MKQIBA140DBad0ooizXbO2w7cyL73vYIWrFRtfjm0yk+oZTvBDD7UsmQailccky8EqZJ/kOmVSfSlk61s3rQn6qdyJYEXXnutpa5gPR6CXdZbbVPhm6z7adXIRxVptCHg566TizefBOS+mng6hwKBgQCp4XJMSSopxOWBiziea+l4RC7mg+Lpdy5x6y6O8IUYQvWSVAHwbgPMuaTi1DJUsbFMuKXVMfTFhn6F+YjLuMOXYtyozOp2GqJkwxBM1T9JGi4tgdB4njDGmk1ZQLEKIONqXKXd0S9gIRArneDJZUSCewMf+rVLc/G33C1aTbciBQKBgQCEs0+J0i1H+z+9Ws728lMT1ntDzM4mphQ2lhrS7iBrwysh3uDhifbzvG+1ZPI7SE8a7CAGvJU0AjCGGuSFJCA4+/14H3C42+4z4VJEHVq7kgVh6dflFlnFYnTncdwy5CdAJfVOtA+YseGbc607skpG6LvamxWQnVCrjzBuBEgdxQKBgDDNVjN6FUW4jaIAZ7yDDagCFmMcYjRli48oW9CuYd3NZpSp04DJaggHEMok4WyZO3Dp3qH3XvTbpT9Bpz23D2FPAkrvyy8wiZRewTEBVdPfVIK4NzZfY226aBwKzJE3T31/rhqh/HUmKmoNScUxdVPymLw4HprVbQw/kTvO9ZwtAoGBAMgjRN1DRgaLGV4tLGajsiiNNs4WLNqiW8UG0sz5elBE5vQimUdT5OMRBS9UQzr9G4gxc4jQoGRhho/i4ZlmtDa4zVW49B1q17+e5H0C5tx6z6F7wBrflgHV0MGC821nlpab4mz3aEmtoiYdKFIsFSuIozStbB7GiFhtj5YO8fLK
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhpdu6HWph4CmAGt3CrESpylxtaL2vHt2ewABf0/NTF4SvwivHfT5j9oJ7vkHoYW8Ob/Dczyvpwfjexpb2IyCaJA7xt2xPfRKWTfBzzxjtiJUbeSlVYZlqOgwG/eVfKNEjCI1TdaOAiRi4DnWJAeFVf74Rq3/WDYbEBaEiHGxRSFBYZQstP7R3EXUNVCGGGeuX2aaQtlUSmcYPtFz4r1N7y62J7p1WGyZsP/eiODawv3gpLFPsphsEggMViAmAtgnQE7BsjgYH3iCiGu9kEBKpuyNi4X0jBDp6UaWcl+ehi+mX4NMe9LRg3qfqWButdRwnJpGjltyWAWsbUaGzBgBLwIDAQAB
  notifyUrl: http://j57e974d.natappfree.cc
  returnUrl: http://localhost:8081 # 回调地址前缀
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do # 沙箱支付网关
  format: JSON
  charset: utf-8
  signType: RSA2

auth:
  code: bb1d57a6-da4f-4052-b3f5-398b9c629f91

# 高德地图配置
amap:
  key: 8fda05360a3952f57930da3919c62df0 # 请替换为实际的高德地图Web服务API Key

# 路线推荐配置
route:
  recommendation:
    max-daily-generate: 5  # 每日最大生成次数
